name: enginner_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_native_splash: ^2.4.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  firebase_core: ^3.2.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.4
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  lottie: ^3.1.2
  skeletonizer: ^1.4.2
  uuid: ^4.5.0
  flutter_animate: ^4.5.0
  barcode_scan2: ^4.3.3
  barcode_widget: ^2.0.4
  cron: ^0.6.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.69.0
  intl: ^0.19.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#19173D"
  image: assets/icons/business.png

  android_12:
    image: assets/icons/business.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/onboarding/
    - assets/images/verify_email/
    - assets/images/succes/

  # fonts:
